### ISSUE TITLE
Display latest statistics first and some UX/UI suggestions

### ISSUE THREAD

**Issue by clnhs** [jeremymoreau/covid19mtl#10]
Hi,

First of all, thank-you for putting that statistics page up for all of us Montrealers. Merci d'avoir mis en ligne cette page d'information et de statistiques pour nous-autres montréalais. 

However, I believe the default display of data on the animated cases map and age-group barchart is misleading as, instead of showing the latest statistics, the earliest data from the datasets is displayed instead of the latest.

To prevent unintentionally misleading people, and to match the rest of the page already displaying the latest data, I believe the default vue should be of the latest data until a user clicks/taps on the play button. 

As to other suggestions:
- Perhaps adding more emphasis on the current date displayed during playback might help better/faster reading
- Main numbers should be put in bold (or at least bolder) 
- The map automatically grabs the mouse preventing page scrolling: perhaps doing it the Google Maps-way and blocking zoom on the map display unless CTRL key is pressed could enhance usability
- On mobile, the same thing happens when I tap inside a chart or map while wanting to scroll, perhaps a tap-and-release should be expected before engaging with these views, so as to not block scrolling.
- On mobile, I am unable to properly interact with the map – can't zoom in or out, and the map itself is stuck in a small square inside the map view.

I would attempt doing the changes myself, but as I have stayed away from web technologies and git for 5 years now and am only getting back into it now, I'll limit myself to suggestions.

P.S.: This project may attract many contributors and people who may want to fork it to adapt it to their cities; it may therefore be beneficial to introduce some contribution guidelines.

**Comment by jeremymoreau** [comment]
Thanks for the comments and suggestions :)

I agree that it would be better for the choropleth map and animated bar plots to show the latest date by default. I actually tried to implement this once, but while I managed to change the default value on the slider, this didn't update the map values until the slider was moved. I don't think there's currently a way to set a default frame in the plotly express API (https://plotly.github.io/plotly.py-docs/generated/plotly.express.choropleth.html), but it might be possible to do something with the lower-level Graph Objects API. I'll take another look into this.

> - Perhaps adding more emphasis on the current date displayed during playback might help better/faster reading

I could try making the current date bold. Not the highest priority on the list of things to do right now, though.

> - Main numbers should be put in bold (or at least bolder)

I just tried switching them to bold, but not sure I like how it looks (subjective, I know). Maybe a medium-weight font would look better, but then I'd need to add a web font that supports more weights. Won't change for now. Thousands separators would also be nice.

> - The map automatically grabs the mouse preventing page scrolling: perhaps doing it the Google Maps-way and blocking zoom on the map display unless CTRL key is pressed could enhance usability
> - On mobile, the same thing happens when I tap inside a chart or map while wanting to scroll, perhaps a tap-and-release should be expected before engaging with these views, so as to not block scrolling.

I agree that the zooming behaviour is problematic, particularly on mobile. Plotly, however, currently only gives the option to either enable or disable zooming, so that's all I can do for now. It's a compromise, but I've opted to disable zooming since it makes the experience better on mobile (and regular pinch to zoom still works). On desktop, it's still possible to zoom using the +/- buttons in the modebar. Note that for the map there appears to be a bug that prevents the +/- buttons from working unless the user first pans the map (will need to wait for upstream fix). This does not affect the other figures.

> - On mobile, I am unable to properly interact with the map – can't zoom in or out, and the map itself is stuck in a small square inside the map view.

Yes, the map is very suboptimal on mobile currently (and used to be even worse, see #5). My options in styling the map differently on mobile are however limited because the entire map view is rendered as an SVG. I've tried making the "bounding box" of the map view resize dynamically to fill all the available space, but haven't figured out how to get that working yet. I might investigate using plotly.express.choropleth_mapbox instead of plotly.express.choropleth to see if that offers a better experience on mobile.

In regards to contribution guidelines, I'll add them if/when there are more active contributors.

**Comment by jeremymoreau** [comment]
I switched the map to use tile-based instead of outline-based maps (see b94f92716613075aa2564540ff7723b1d17283d0) and it works much better on mobile now! I re-enabled zoom for the map, however, since I can't set different default zoom levels on desktop and mobile (the default on mobile is a bit too zoomed in).

**Comment by jeremymoreau** [comment]
Changed choropleth map and age plot to display the latest date by default in 5f54d01c31159095c192105203b7c8a4849dab20, thanks to solution here: https://community.plotly.com/t/defining-default-starting-frame-with-plotly-express-animation/38636
Closing this issue for now.
