### ISSUE TITLE
Add test positivity rate

### ISSUE THREAD

**Issue by mschoettle** [jeremymoreau/covid19mtl#48]
I suggest to show the test positivity rate instead of the number of negative tests in the boxes on top. The rate is already present in the QC data in the `psi_quo_pos_t` column. Ideally, the rates for Montreal and Quebec are shown. Also it should be shown that the rate is from a day earlier than the data (so usually 2 days before the current date).

I tried the following but not sure about the looks:

<img width="238" alt="Screen Shot 2020-12-24 at 23 43 59" src="https://user-images.githubusercontent.com/9328433/103119647-3a9bb180-4642-11eb-95f1-eb640f686e32.png">

**Comment by jeremymoreau** [comment]
I agree that the test positivity rate is more useful. I'd be more inclined to replacing the "Diagnostic tests (QC)" plot with this data and using the mini box to display the vaccine count/% vaccinated info. The absolute cumulative counts of negative diagnostic tests aren't all that useful, so I'd just drop that info altogether. We could add more mini boxes, but we'd need to add two at a time and it's a bit more work since I'd have to redo the responsive layout (it goes from 1x8 to 2x4, and 4x2 on small displays/mobile).

**Comment by jeremymoreau** [comment]
I've replaced the previous "Diagnostic tests (QC)" figure with a figure showing test positivity rate (for both QC and MTL).
![test pos](https://user-images.githubusercontent.com/7446564/103196102-cca0f580-48a0-11eb-8066-c9395e1c4250.png)

**Comment by mschoettle** [comment]
Great, thanks! I think having the plot is great. Still would like to add it to the mini boxes but will have to see how we can manage that. I might try to separate MTL and QC into two separate pages so the mini boxes are not too crowded.

**Comment by jeremymoreau** [comment]
Sounds good, maybe we could have one row of mini boxes for QC and one row for MTL? It'd be good if we could make a list of mini boxes we want to add so that we can plan the layout (e.g. adding 4 boxes would work well, desktop 2x6 → iPad/small screens 4x3 → mobile 6x2).

**Comment by mschoettle** [comment]
Good idea. I'll create a separate issue for this.
