### ISSUE TITLE
Add vaccine doses administered

### ISSUE THREAD

**Issue by mschoettle** [jeremymoreau/covid19mtl#51]
It would probably be enough to add it to the boxes on top (if there's enough space). Not sure if a graph is necessary.

The data is available from these sources:

* https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/csv/situation-au-quebec-en.csv
* https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/csv/doses-vaccins-en.csv (contains break down of different regions)
* https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/csv/synthese-7jours-en.csv (contains the last 7 days)

**Comment by jeremymoreau** [comment]
I think we could replace the "Negative tests (QC)" box with this since it seems more useful (and the negative tests are already in one of the plots). It might also be interesting to display an approximate percentage of the QC population vaccinated (e.g. for today, (11171/2)*100/8586528 = 0.07%). This assumes that 2 doses == 1 person vaccinated, which isn't exactly accurate since it's more like n people received the first dose and are waiting 21 days for the 2nd dose. Hopefully they will eventually start publishing the number of people who have received the complete 2-dose schedule as well.

**Comment by jeremymoreau** [comment]
Added in #56. Will also add to mini boxes later.
