### ISSUE TITLE
Add back active hospitalisations figure

### ISSUE THREAD

**Issue by mschoettle** [jeremymoreau/covid19mtl#54]
I commented in #52 but it's already closed.

I think we should add back the active hospitalization figure:

<img width="476" alt="Screen Shot 2020-12-28 at 07 19 23" src="https://user-images.githubusercontent.com/9328433/103213896-114a8200-48dd-11eb-937b-2def7ac607b4.png">

Unfortunately, there seems to be no separate data for Montreal so it is QC only.

Another way would be to combine the new figure and this one and add a hover tooltip with specific data like new hospitalizations for a particular day.

**Comment by jeremymoreau** [comment]
Sure, sounds good. Maybe I can try adding a 2nd y-axis to the current figure for the old figure data (since the scales are very different).

**Comment by jeremymoreau** [comment]
Done in 9c057c5bb1bd635b43bd19e7794b144995fffa0b.

Also added a 2nd y-axis for new cases/deaths/etc. line charts and modified them to display 7-day rolling averages instead of the raw daily counts.

![hospitalisations](https://user-images.githubusercontent.com/7446564/103403901-0d05ab00-4b0f-11eb-9115-097b6699acc7.png)
